In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_excel('Inc_Desc.xls')
testdataset = pd.read_excel('test.xls')

In [3]:
incwords = ['negotiation','qc','nrp','pwc','application','9149','liability','promise','p2p','annual','ideal','payments','payment','mopf','creation','benefit','cofc','account','accounts','bancs','lo','enforcement','arrears','variation','closure','master']
print(len(incwords))
#For train data
X_trn=[]
sTrn = set()
for i in range(0, len(dataset)):
    desc = dataset['Description'][i].lower()    
    #keys = re.sub(incwords, ' ', desc)
    desc = desc.split()    
    desc = [word for word in desc if word in set(incwords)]
    #print('filtered version:',desc)    
    for i in range(0, len(desc)):
        sTrn.add(desc[i])         
    
    desc = ' '.join(desc)
    X_trn.append(desc)

#For test data    
X_tst = []
sTst = set()
for i in range(0, len(testdataset)):
    testdesc = testdataset['Description'][i].lower()
    testdesc = testdesc.split()
    testdesc = [word for word in testdesc if word in set(incwords)]
    for i in range(0, len(testdesc)):
        sTst.add(testdesc[i])
    
    testdesc = ' '.join(testdesc)
    X_tst.append(testdesc)

print('Set Train:',sTrn)
print('Set Test:',sTst)

25
Set Train: {'pwc', 'payments', 'liability', 'enforcement', 'variation', 'promise', '9149', 'payment', 'annual', 'mopf', 'account', 'master', 'application', 'accounts', 'benefit', 'bancs', 'ideal', 'closure', 'cofc', 'qc', 'nrp', 'lo', 'creation', 'negotiation', 'arrears'}
Set Test: {'pwc', 'liability', 'payments', 'enforcement', 'variation', '9149', 'payment', 'annual', 'mopf', 'account', 'master', 'application', 'accounts', 'benefit', 'bancs', 'ideal', 'closure', 'cofc', 'qc', 'nrp', 'lo', 'creation', 'negotiation', 'arrears'}


In [4]:
xtrnLen = len(sTrn)
xtstLen = len(sTst)

print("A",xtrnLen)
print("B",xtstLen)

# Creating the Bag of Words model For train Data
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = xtstLen) if xtrnLen >= xtstLen else CountVectorizer(max_features = xtrnLen)
X = cv.fit_transform(X_trn).toarray()
y = dataset.iloc[:, 1].values

# Creating the Bag of Words model for test data
#from sklearn.feature_extraction.text import CountVectorizer
#cv = CountVectorizer(max_features = len(X_trn))
X_test = cv.fit_transform(X_tst).toarray()
y_test = testdataset.iloc[:, 1].values

A 25
B 24


In [5]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X, y)

GaussianNB(priors=None, var_smoothing=1e-09)

In [6]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)

In [7]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[2, 0, 0, 0, 0, 2, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 5, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [8]:
X.shape

(7, 24)

In [9]:
X_test.shape

(21, 24)

In [10]:
print(y_test)
print(y_pred)

[4 5 6 3 3 1 1 2 0 3 0 0 3 3 4 6 5 1 0 2 3]
[4 5 6 5 4 1 1 2 5 5 0 5 5 5 4 6 5 1 0 2 5]


In [11]:
X

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        1, 1],
       [1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0]], dtype=int64)

In [12]:
type(X_tst)

list

In [13]:
print('X_tst:',X_tst)
X_test

X_tst: ['accounts bancs', 'arrears variation', 'lo enforcement', 'liability', 'annual account', 'mopf payments', 'payment payments', 'cofc closure master', 'creation', '9149', 'qc nrp pwc application creation', 'application', '9149', '', 'account', 'lo', 'negotiation', 'payment', 'qc nrp', 'benefit', 'ideal']


array([[0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
        1, 0],
       [0, 0, 0, 0, 1

In [14]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
randomforestClassifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 0)
randomforestClassifier.fit(X, y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='entropy', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=20,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [15]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
cmr = confusion_matrix(y_test, y_pred)
cmr

array([[2, 0, 0, 0, 0, 2, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 5, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [16]:
y_test

array([4, 5, 6, 3, 3, 1, 1, 2, 0, 3, 0, 0, 3, 3, 4, 6, 5, 1, 0, 2, 3],
      dtype=int64)

In [17]:
y_pred

array([4, 5, 6, 5, 4, 1, 1, 2, 5, 5, 0, 5, 5, 5, 4, 6, 5, 1, 0, 2, 5],
      dtype=int64)

In [18]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

cm


array([[2, 0, 0, 0, 0, 2, 0],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 4, 1, 1, 0],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [19]:
print(y_test)
print(y_pred)

[4 5 6 3 3 1 1 2 0 3 0 0 3 3 4 6 5 1 0 2 3]
[4 5 6 3 4 1 1 2 5 3 0 5 3 5 4 6 5 1 0 2 3]


In [20]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X, y)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1, 0, 0, 0, 0, 0, 3],
       [0, 3, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 5],
       [0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 2]], dtype=int64)

In [21]:
print(y_test)
print(y_pred)

[4 5 6 3 3 1 1 2 0 3 0 0 3 3 4 6 5 1 0 2 3]
[4 5 6 6 4 1 1 2 6 6 0 6 6 6 4 6 5 1 6 2 6]
